"""Property-based tests for `services.event` validators.

Hypothesis explores the input space for the pure validators where
example-based tests can only sample a handful of cases. Targets:

    - validate_event_datetime  → "future-only" + "end > start" invariants
    - validate_segments        → location_index range, contiguous order,
                                 no overlap, within event window
    - _normalise_review_text   → whitespace-only → None contract

All four validators are pure: no DB, no HTTP, no time freeze needed.
The base strategies live in `tests/hypothesis_strategies.py` so the
example-based suite can use the same building blocks.
"""
from __future__ import annotations

from datetime import UTC, datetime, timedelta
from unittest.mock import MagicMock

import pytest
from fastapi import HTTPException
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from app.models.event import SegmentRequest
from app.services import event as event_service
from app.services.rating import _normalise_review_text
from tests.hypothesis_strategies import (
    aware_datetime,
    contiguous_segments,
    event_window,
)


@pytest.fixture
def db() -> MagicMock:
    """Override the conftest session-scoped db so this file doesn't try
    to contact a real Supabase. The validators under test are pure;
    the autouse cleanup_test_users fixture takes ``db`` as an argument
    and would otherwise resolve the real one."""
    return MagicMock(name="supabase_client")


_HEALTH_CHECKS = [HealthCheck.function_scoped_fixture]


# ── validate_event_datetime ─────────────────────────────────────────────────


@given(window=event_window())
@settings(max_examples=200, suppress_health_check=_HEALTH_CHECKS)
def test_future_window_with_end_after_start_always_passes(window: tuple[datetime, datetime]) -> None:
    """For any future window with end > start, validate_event_datetime never raises."""
    start, end = window
    event_service.validate_event_datetime(start, end)


@given(start=aware_datetime(days_min=1, days_max=365))
@settings(max_examples=100, suppress_health_check=_HEALTH_CHECKS)
def test_end_before_or_equal_start_always_400(start: datetime) -> None:
    """end_datetime ≤ start_datetime must always raise 400."""
    with pytest.raises(HTTPException) as exc:
        event_service.validate_event_datetime(start, start)
    assert exc.value.status_code == 400

    earlier = start - timedelta(seconds=1)
    with pytest.raises(HTTPException) as exc:
        event_service.validate_event_datetime(start, earlier)
    assert exc.value.status_code == 400


@given(
    days_in_past=st.integers(min_value=1, max_value=365),
    duration_minutes=st.integers(min_value=1, max_value=240),
)
@settings(max_examples=100, suppress_health_check=_HEALTH_CHECKS)
def test_past_start_without_allow_past_always_400(
    days_in_past: int, duration_minutes: int,
) -> None:
    start = datetime.now(UTC) - timedelta(days=days_in_past)
    end = start + timedelta(minutes=duration_minutes)
    with pytest.raises(HTTPException) as exc:
        event_service.validate_event_datetime(start, end)
    assert exc.value.status_code == 400


# ── validate_segments ──────────────────────────────────────────────────────

# Hypothesis composite that materialises (window, location_count, segments)
# in lock-step. Generating them independently and then asking
# `contiguous_segments` to draw doesn't compose well — every test has to
# .example() once, which is the anti-pattern Hypothesis itself flags.
@st.composite
def _valid_event_with_segments(
    draw: st.DrawFn,
) -> tuple[datetime, datetime, int, list[SegmentRequest]]:
    start, end = draw(
        event_window(duration_min_minutes=120, duration_max_minutes=12 * 60),
    )
    location_count = draw(st.integers(min_value=1, max_value=4))
    segments = draw(
        contiguous_segments(
            location_count=location_count,
            event_start=start,
            event_end=end,
        ),
    )
    return start, end, location_count, segments


@given(case=_valid_event_with_segments())
@settings(max_examples=120, suppress_health_check=_HEALTH_CHECKS)
def test_contiguous_in_window_segments_always_valid(
    case: tuple[datetime, datetime, int, list[SegmentRequest]],
) -> None:
    """Contiguous, in-window segments generated by the strategy always pass."""
    start, end, location_count, segments = case
    if not segments:
        return
    event_service.validate_segments(segments, location_count, start, end)


@given(
    window=event_window(duration_min_minutes=120, duration_max_minutes=12 * 60),
    location_count=st.integers(min_value=1, max_value=4),
    bad_index_offset=st.integers(min_value=0, max_value=10),
)
@settings(max_examples=80, suppress_health_check=_HEALTH_CHECKS)
def test_segment_with_out_of_range_location_index_400(
    window: tuple[datetime, datetime], location_count: int, bad_index_offset: int,
) -> None:
    """Out-of-range location_index always raises 400."""
    start, end = window
    segs = [
        SegmentRequest(
            location_index=location_count + bad_index_offset,  # always out of range
            order_index=0,
            start_datetime=start,
            end_datetime=start + timedelta(minutes=30),
        ),
    ]
    with pytest.raises(HTTPException) as exc:
        event_service.validate_segments(segs, location_count, start, end)
    assert exc.value.status_code == 400


# ── rating.review_text normalisation ────────────────────────────────────────


@given(
    leading=st.text(alphabet=" \t\n\r", max_size=20),
    body=st.text(min_size=1, max_size=500),
    trailing=st.text(alphabet=" \t\n\r", max_size=20),
)
@settings(suppress_health_check=_HEALTH_CHECKS)
def test_normalise_strips_whitespace_and_keeps_body(
    leading: str, body: str, trailing: str,
) -> None:
    """Surrounding whitespace removed; substantive body kept verbatim."""
    raw = f"{leading}{body}{trailing}"
    cleaned = _normalise_review_text(raw)
    if body.strip():
        assert cleaned == raw.strip()
    else:
        assert cleaned is None


@given(text=st.text(alphabet=" \t\n\r", min_size=0, max_size=200))
@settings(suppress_health_check=_HEALTH_CHECKS)
def test_whitespace_only_input_normalises_to_none(text: str) -> None:
    """Whitespace-only or empty review text is always None."""
    assert _normalise_review_text(text) is None


def test_none_input_passes_through() -> None:
    """`None` short-circuits without trimming."""
    assert _normalise_review_text(None) is None
